### ISSUE TITLE
Allow filtering list of countries

### ISSUE THREAD

**Issue by dalewking** [juanpabloprado/CountryPicker#1]
For our app we need only a specific subset of all countries

**Comment by Shajeel-Afzal** [comment]
We also need to show only a certain set of countries not all.

**Comment by juanpabloprado** [comment]
Hi, I get the list of countries from the Android API by calling Locale.getISOCountries() in the method getAllCountries() inside CountryPicker.java class.

**Comment by dalewking** [comment]
And you need to add a way to set a callback or something to select which of those countries to actually include

**Comment by juanpabloprado** [comment]
You can mutate the list CountryPicker.countries as in line 75(CountryPicker.java) when sorting the countries based on country name occurs. Add a callback call there. e.g. `mListener.beforeSetupCountries(countries);` The interface would look something like.

``` java
public interface CountryPickerListener {
  void beforeSetupCountries(List<Country> countries);
  void onSelectCountry(String name, String code);
}
```

**Comment by dalewking** [comment]
I agree that it is a simple modification to allow filtering the countries, but this is supposed to be a library which means I simply add it as a dependency and cannot modify the source code.

**Comment by juanpabloprado** [comment]
Pull requests welcome

**Comment by juanpabloprado** [comment]
Pull requests welcome
